set (APP_NAME "toy_robot")
set (APP_SOURCE_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}/src)
set (APP_ROOT_DIRECTORY ${CMAKE_CURRENT_LIST_DIR}/)

set (CMAKE_CXX_STANDARD 17)
set (CMAKE_CXX_STANDARD_REQUIRED ON)
